### ISSUE TITLE
QQ互助交流群：611838098

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/17wanxiaoCheckin#30]
设置了验证暗号：0（就是数字0）

**Comment by bananas12138** [comment]
群都没了

**Comment by ReaJason** [comment]
> 群都没了

可以了

**Comment by lllhr12311** [comment]
群暗号变了吗

**Comment by AlexLe78** [comment]
求群号啊！！！

**Comment by ReaJason** [comment]
> 求群号啊！！！

可以了，就这个群号，因为不想建其他群了，所以满了500就关了

**Comment by GCParr0t** [comment]
群都没了哇，，。digital ocean好像没有云函数，该咋搞呢，，

**Comment by ReaJason** [comment]
现在这个群已经扩到 2000 了

**Comment by buerrr** [comment]
搜不到群...

**Comment by ReaJason** [comment]
> 搜不到群...

再试试

**Comment by buerrr** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin] QQ互助交流群：611838098 (#30)





  
搜不到群...
  
再试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you commented.

可以了 感谢！Message ID: ***@***.***&gt;

**Comment by mhb518340** [comment]
暗号变了吧，输入 0 显示错误。。。。
